### ISSUE TITLE
Is this package work?

### ISSUE THREAD

**Issue by technoiswatchingyou** [arthurmbandeira/nodejs-currency-converter#1]
Hi. Could you tell me, please, is this package in a real working state? If 'yes', could you write some working example for me?

Best,
Andrei.

**Comment by arthurmbandeira** [comment]
Hi, unfortunately this packge isn't working anymore, since fixer api do not remain free to use :disappointed:.
I intend to update it as soon I have the time to, but feel free to fork it or make a pull request and do the ~apparently~ simple update using fixer.io apikey (details [here](https://github.com/fixerAPI/fixer)).
I hope this helps.
Best regards,
Arthur.
